### ISSUE TITLE
HTML ends up on the actual page when providing the "Link to" parameter in Upload/edit file

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#4] opened 2018-04-17 09:05 UTC
## ON MW-1.27.4, MW-1.29.2 & MW-1.30.0
When selecting the below image properties:

![general](https://user-images.githubusercontent.com/6680027/38859321-0c227e9e-422e-11e8-96f0-3424f18d895b.png)
![image](https://user-images.githubusercontent.com/6680027/38858895-2cae8c30-422d-11e8-9925-e4709c2edcf9.png)

What is saved on the page is:
```<a data-mce-href="Some link to another page" href="Some link to another page">[[File:20171109 172708.jpg|300px|link=Some link to another page|alt=Some alternative text|none|middle|thumb|20171109 172708.jpg]]</a>```

**Comment by duncan-crane** [comment] 2018-04-18 12:22
Hi Felipe

I included what I hope is a fix for this in my latest upload to the master branch.  Would you let me know if this works for you?

Many thanks - Duncan

**Comment by jongfeli** [comment] 2018-04-20 07:02
Hello Duncan

I tested this but the problem is still there. It only happens when you add a value for the `Link to` parameter. On all MW versions tested you end up with the below code on the wikipage after you save the page.

`<a data-mce-href="Some link to another page" href="Some link to another page">[[File:20171109 172708.jpg|300px|link=Some link to another page|right|middle|thumb]]</a>`

**Comment by duncan-crane** [comment] 2018-04-22 16:50
Hi Felipe

I've made quite a lot of changes to this functionality over the weekend so (see issue #3).  In the course of testing this issue seems to be resolved for me.  Please do let me know if it is still occurring for you?

Many thanks
Duncan

**Comment by jongfeli** [comment] 2018-04-23 09:21
I can not reproduce this, seems to be fixed. 

I did stumble into something I can not reproduce at the moment. I sometimes end up with the below code on the page:

```
[[File:20171109 172708.jpg|none|middle|thumb|20171109 172708.jpg]]

<*****>
``` 
I will try to reproduce this but with no luck at the moment. But maybe you recognize the syntax and know immediately what the problem is :grinning: 

It can also trigger #15

**Comment by duncan-crane** [comment] 2018-04-23 18:17
Thanks Felipe
This probably relates to the changes I made at the weekend but may be a 'use case' I overlooked.  Would you let me have the original wikicode - or at least what you expected it to be if you entered it into TinyMCE?

**Comment by jongfeli** [comment] 2018-04-26 05:22
Hello Duncan. The code is just that file mentioned above. I do not know where the `<*****>` comes from. @poVoq also noticed this in #13. I will try to reproduce this.

**Comment by duncan-crane** [comment] 2018-04-28 16:30
Hi Felipe
I've not been able to reproduce this error but I did find some of the code I uploaded last week wasn't always finding and replacing some html spans, which I think may have been the cause of this.  If you have time would you see if you can reproduce the error when using the code I uploaded to the master branch today?
Many thanks, Duncan
Duncan

**Closed as completed** 2018-05-04 15:00 UTC

**Comment by jongfeli** [comment] 2018-05-14 12:11
I still can't reproduce this.
